.eslintignore, blocks/columns-bd/columns-bd.css, blocks/columns-bd/columns-bd.js, blocks/columns/columns.css, blocks/footer/footer.css, blocks/footer/footer.js, blocks/header/header.css, blocks/header/header.js, blocks/hero/hero.css, blocks/hero/hero.js, blocks/products/products.css, blocks/products/products.js, blocks/slector/selector.css, head.html, styles/styles.css
Add two-columns-with-images-component
Clean header and footer layout
Remove scripts from head.
https://two-column-with-images-component--helix-poc--enake.hlx.page/cl-offer-vcd-opt
https://main--helix-poc--enake.hlx.page/cl-offer-vcd-opt
=> Add two-columns-with-images-component, clean header and footer layout

head.html
Test URLs:
- Before: [https://main--<repo>--<owner>.hlx.page/](https://main--helix-poc--enake.hlx.page/)
- After: [https://<branch>--<repo>--<owner>.hlx.page/](https://lucia_work--helix-poc--enake.hlx.page/)
=> Adding Bootstrap to Header

blocks/awards/awards.css, blocks/awards/awards.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/cl-offer-vcd-opt
- After: https://awards-section--helix-poc--enake.hlx.page/cl-offer-vcd-opt
=> Add awards section

blocks/columns-two/columns-two.css, blocks/columns-two/columns-two.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/cl-offer-vcd-opt
- After: https://columns-two--helix-poc--enake.hlx.page/cl-offer-vcd-opt
=> Add columns-two component

blocks/b-banner/b-banner.js
Test URLs:
Before: [https://main----.hlx.page/](https://main--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)](https://main--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)
After: [https://----.hlx.page/](https://DEX-13735--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)](https://DEX-13735--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)
=> Update b-banner component for the new required LP

blocks/c-productswithvpn/c-productswithvpn.css, blocks/c-productswithvpn/c-productswithvpn.js, styles/styles.css
=> Block : c-productswithvpn - Updates

blocks/b-productswithselectors/b-productswithselectors.js
Please always provide the [GitHub issue(s)](https://github.com/enake/helix-poc/issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #
Test URLs:
Before: [https://main----.hlx.page/](https://main--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)](https://main--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)
After: [https://----.hlx.page/](https://selector_update--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)](https://selector_update--helix-poc--enake.hlx.page/business/en/winback-2023-independence-day)
=> Update selector to include 100 devices

blocks/footer/footer.js, scripts/adobeDataLayer.js, scripts/delayed.js, scripts/scripts.js
=> Implements adobe data layer & adobe analytics

blocks/b-banner/b-banner.css
=> b-banner smaller header tittle

blocks/b-banner/b-banner.css, blocks/b-boxes/b-boxes.js, blocks/b-dropdownbox/b-dropdownbox.js, blocks/b-loadselectors/b-loadselectors.js
=> eslint fixes + update on b-banner

blocks/b-banner/b-banner.css
=> b-banner - updates

scripts/scripts.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/
- After: https://feature-geoip--helix-poc--enake.hlx.page/
=> Implements geoIp

blocks/header/header.js, scripts/adobeDataLayer.js, scripts/scripts.js, scripts/utils.js
Test URLs:
- After: https://geoip--helix-poc--enake.hlx.page/consumer/en/new/last-offer
=> Removes geoIp Implementation

blocks/b-dropdownbox/b-dropdownbox.css, blocks/c-dropdownbox/c-dropdownbox.css, blocks/c-dropdownbox/c-dropdownbox.js
=> Updates on c-dropdownbox

blocks/footer/footer.js, scripts/scripts.js
=> Fixing footer.js

tools/sidekick/config.json
Test URLs:
- After: https://config--helix-poc--enake.hlx.page/consumer/en/new/last-offer
=> Adds config for production env

blocks/b-productswithselectors/b-productswithselectors.js, blocks/c-productswithvpn/c-productswithvpn.js, blocks/c-productswithvpn2/c-productswithvpn2.js, blocks/c-top-comparative-with-text/c-top-comparative-with-text.js, scripts/scripts.js
=> fixes full price

blocks/b-productswithselectors/b-productswithselectors.css, blocks/b-productswithselectors/b-productswithselectors.js, blocks/c-productswithvpn/c-productswithvpn.js, blocks/c-productswithvpn2/c-productswithvpn2.js, scripts/scripts.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/ransomwaretrial
- After: https://header-block-update--helix-poc--enake.hlx.page/business/en/ransomwaretrial
=> Display fixes for b-productswithselectors

.github/pull_request_template.md, scripts/scripts.js
Test URLs:
- After: https://default_language_fix--helix-poc--enake.hlx.page/consumer/en/new/last-offer
=> default_language_fix

scripts/adobeDataLayer.js, scripts/delayed.js, scripts/scripts.js
Test URLs:
- After: https://tracking--helix-poc--enake.hlx.page/consumer/en/new/last-offer
=> Implements a method to load AdobeDTM & GTM at different times.

.github/pull_request_template.md, scripts/vendor/store2015.js
Test URLs:
- After: https://foreach_fix_in_store2015--helix-poc--enake.hlx.page/consumer/en/new/last-offer
=> store2015 forEach fix

scripts/utils.js
Test URLs:
- After: https://code_update--helix-poc--enake.hlx.page/consumer/en/new/last-offer
=> Update get DEFAULT_LANGUAGE  + get_Section

head.html
Fix #DEX-14202
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/it/mr-summer-ready-july-2023
- After: https://DEX-14202-Meta-robots-no-index-no-follow--helix-poc--enake.hlx.page/business/it/mr-summer-ready-july-2023
=> DEX-14202-Robots no index no follow

scripts/delayed.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/new/ultimate-flv1
- After: https://onetrust--helix-poc--enake.hlx.page/consumer/en/new/ultimate-flv1
=> Removes GTM and Cookiebot based on a parameter.

e2e/index.js, scripts/vendor/store2015.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/affiliate-sbs-50
- After: https://<branch>--helix-poc--enake.hlx.page/business/en/affiliate-sbs-50
=> Store2015 update

blocks/b-productswithinputdevices/b-productswithinputdevices.css, blocks/b-productswithinputdevices/b-productswithinputdevices.js, blocks/b-productswithinputdevices/b-productswithinputdevices.scss, blocks/c-productswithvpn2/c-productswithvpn2.css, blocks/c-productswithvpn2/c-productswithvpn2.js, blocks/c-productswithvpn2/c-productswithvpn2.scss, e2e/index.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/renew/vpn-pass-dip
- After: https://banner_update--helix-poc--enake.hlx.page/consumer/en/renew/vpn-pass-dip
=> [DEX-14422] - New lp

blocks/b-banner/b-banner.css, blocks/b-banner/b-banner.scss, blocks/c-productswithvpn/c-productswithvpn.css, blocks/c-productswithvpn/c-productswithvpn.js, blocks/c-productswithvpn/c-productswithvpn.scss, e2e/json-tests/price-validation.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/renew/b2s-ultpsts-opt
- After: https://Back-to-school--helix-poc--enake.hlx.page/consumer/en/renew/b2s-ultpsts-opt
=> Add styling for when there is no vpn addon

blocks/c-productswithvpn/c-productswithvpn.js, scripts/scripts.js, scripts/utils.js, scripts/vendor/store2015.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/renew/vpn-pass-dip
- After: https://banner_update--helix-poc--enake.hlx.page/consumer/en/renew/vpn-pass-dip
=> Banner update

blocks/b-banner/b-banner.css, blocks/b-banner/b-banner.scss, blocks/c-productswithvpn/c-productswithvpn.css, blocks/c-productswithvpn/c-productswithvpn.scss
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/flashsalegz
- After: https://fixes--helix-poc--enake.hlx.page/business/en/flashsalegz
=> [DEX-14564] Aliniere butoane zona de buy

components/svg-loader/svg-loader.js, e2e/index.js, e2e/json-tests/price-validation.js, tools/sidekick/config.json, tools/sidekick/library.html
Fix #DEX-14552
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/ransomwaretrial
- After: https://DEX-14552--helix-poc--enake.hlx.page/business/en/ransomwaretrial
=> DEX-14552-Sidekick library

blocks/b-productswithselectors/b-productswithselectors.css, blocks/b-productswithselectors/b-productswithselectors.scss, scripts/delayed.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/flashsalegz?tt=dsfds
- After: https://fixes--helix-poc--enake.hlx.page/business/en/flashsalegz?tt=dsfds
=> [DEX-14558] - Cookies pop-up not translated

blocks/b-productswithinputdevices/b-productswithinputdevices.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/mobile-back-to-work-sep-2023
- After: https://fixes--helix-poc--enake.hlx.page/business/en/mobile-back-to-work-sep-2023
=> Change servers & mailboxes calc logic

blocks/b-productswithinputdevices/b-productswithinputdevices.js, blocks/b-productswithselectors/b-productswithselectors.js, blocks/c-productsboxes/c-productsboxes.js, blocks/c-productswithvpn/c-productswithvpn.js, blocks/c-productswithvpn2/c-productswithvpn2.js, blocks/c-top-comparative-with-text/c-top-comparative-with-text.js, styles/styles.css, styles/styles.scss
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/flashsalegz
- After: https://DEX-14492--helix-poc--enake.hlx.page/business/en/flashsalegz
=> Adding class for hiding buyBtn

blocks/fragment/fragment.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/test
- After: https://fragment-block--helix-poc--enake.hlx.page/consumer/en/test
=> Add fragment block

e2e/json-tests/price-validation.js
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/en/ransomwaretrial
- After: https://consumer-test-updates--helix-poc--enake.hlx.page/business/en/ransomwaretrial
=> Test prices asserts change

blocks/b-banner/b-banner.css, blocks/b-banner/b-banner.scss, blocks/b-buybuttons/b-buybuttons.css, blocks/b-buybuttons/b-buybuttons.js, blocks/b-buybuttons/b-buybuttons.scss, blocks/b-productswithselectors/b-productswithselectors.js, blocks/c-productsboxes/c-productsboxes.js, scripts/scripts.js, styles/styles.css, styles/styles.scss
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/business/de/paidmedia-sbs
- After: https://zuora_update--helix-poc--enake.hlx.page/business/de/paidmedia-sbs
=> Zuora update

blocks/b-banner/b-banner.css, blocks/b-banner/b-banner.scss
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/renew/avfree-ps-opt
- After: https://DEX-14472--new-LP--helix-poc--enake.hlx.page/consumer/en/renew/avfree-ps-opt
=> Quick fix for banner image

scripts/adobeDataLayer.js
Test URLs:
- After: https://fixDataLayer--helix-poc--enake.hlx.page/drafts/test-page/
=> Fix domainPeriod value

scripts/delayed.js, scripts/scripts.js
Test URLs:
- After: https://testingEnv--helix-poc--enake.hlx.page/drafts/test-page/
=> DEX-14722 - Moves adobe launch higher in the execution queue.

scripts/utils.js
Test URLs:
- After: https://DEX-14703--helix-poc--enake.hlx.page/drafts/test-page/
=> DEX-14703 Add adobe mc without the click condition

blocks/b-productswithinputdevices/b-productswithinputdevices.js, blocks/b-productswithselectors/b-productswithselectors.js, scripts/scripts.js, scripts/zuora.js
Test URLs:
- After: https://dex-14692--helix-poc--enake.hlx.page/drafts/test-page/
=> DEX-14692 - Add parameters on buylink btn

fstab.yaml
Test URLs:
- After: https://<branch>--helix-poc--enake.hlx.page/drafts/test-page/
=> Sharepoint

fstab.yaml
=> Revert "Sharepoint"

blocks/b-productswithselectors/b-productswithselectors.js
Test URLs:
- After: https://DEX-14727--helix-poc--enake.hlx.page/drafts/test-page/
=> Display only oldprice

scripts/vendor/store2015.js
Test URLs:
- After: https://dex-14646--helix-poc--enake.hlx.page/drafts/test-page/
=> Update store2015 js

scripts/vendor/store2015.js
Test URLs:
- After: https://dex-14646--helix-poc--enake.hlx.page/drafts/test-page/
=> correction force_country us

blocks/b-banner/b-banner.js
Test URLs:
- After: https://dex-14646--helix-poc--enake.hlx.page/drafts/test-page/
=> update on banner

styles/styles.css, styles/styles.scss
Test URLs:
- After: https://DEX-14888--helix-poc--enake.hlx.page/drafts/test-page/
=> Add a blue button option

blocks/b-buybuttons/b-buybuttons.css, blocks/b-buybuttons/b-buybuttons.scss, blocks/b-dropdownbox/b-dropdownbox.css, blocks/b-dropdownbox/b-dropdownbox.scss, blocks/b-productswithselectors/b-productswithselectors.css, blocks/b-productswithselectors/b-productswithselectors.scss
Test URLs:
- After: https://dex-14837--helix-poc--enake.hlx.page/drafts/test-page/
=> Css responsive updates

styles/styles.css, styles/styles.scss
Test URLs:
- After: https://dex-14837--helix-poc--enake.hlx.page/drafts/test-page/
=> css update for selectors

scripts/lib-franklin.js
Fix #DEX-14786
Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/drafts/test-page/test-vlad
- After: https://DEX-14786--helix-poc--enake.hlx.page/drafts/test-page/test-vlad
=> DEX-14786-Svg-from-drive

blocks/b-productswithinputdevices/b-productswithinputdevices.css, blocks/b-productswithinputdevices/b-productswithinputdevices.js, blocks/b-productswithinputdevices/b-productswithinputdevices.scss
Test URLs:
- After: https://dex-14960--helix-poc--enake.hlx.page/drafts/test-page/
=> adding discount circles for each product

scripts/delayed.js, scripts/zuora.js
Test URLs:
- After: https://zuora_v3--helix-poc--enake.hlx.page/drafts/test-page/
=> Zuora update - sdk removed

blocks/b-banner/b-banner.css, blocks/b-banner/b-banner.scss
Test URLs:
- After: https://Wolves--helix-poc--enake.hlx.page/drafts/test-page/
=> Style correction for chicago wolves lp

scripts/lib-franklin-api.js
Test URLs:
- After: https://DEX-15269--helix-poc--enake.hlx.page/drafts/test-page/
=> DEX-15269 | updated lib-franklin-api file
